-- Planify Pedagogical Brain — estrutura opcional para Supabase/PostgreSQL
-- Esta estrutura serve para evoluir a base offline para banco de dados gerenciável pelo Admin.

create table if not exists pedagogical_material_contracts (
  id text primary key,
  name text not null,
  delivery text not null,
  required_sections jsonb not null default '[]'::jsonb,
  forbidden_patterns jsonb not null default '[]'::jsonb,
  student_pattern jsonb not null default '[]'::jsonb,
  teacher_pattern jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists pedagogical_discipline_lenses (
  id text primary key,
  name text not null,
  focus jsonb not null default '[]'::jsonb,
  avoid jsonb not null default '[]'::jsonb,
  quality_rule text not null,
  created_at timestamptz not null default now()
);

create table if not exists pedagogical_quality_gates (
  id bigint generated by default as identity primary key,
  gate text not null,
  severity text not null default 'hard',
  created_at timestamptz not null default now()
);

create table if not exists pedagogical_question_patterns (
  id bigint generated by default as identity primary key,
  pattern_type text not null,
  structure text not null,
  answer_key_model text not null,
  use_when text not null,
  created_at timestamptz not null default now()
);
