/**
 * Temas de DESIGN das apresentações Planify.
 *
 * Cada tema é um sistema visual completo (paleta, tipografia, fundo, cabeçalho
 * e decoração) aplicado tanto na pré-visualização HTML quanto na exportação
 * para Google Apresentações (PPTX). Módulo de dados puros: pode ser importado
 * no servidor e no cliente.
 */

export const SLIDE_THEME_IDS = [
  "moderno",
  "editorial",
  "minimal",
  "vibrante",
  "academico",
  "lousa",
  "corporativo",
  "neontech",
  "infografico",
  "pastel",
  "natureza",
  "geometria",
  "retro",
  "luxo",
  "startup",
  "oceano",
] as const;

export type SlideThemeId = (typeof SLIDE_THEME_IDS)[number];

export type SlideHeaderKind = "bar" | "ribbon" | "underline" | "block" | "chalk";
export type SlideDecoration = "blob" | "corner" | "line" | "dots" | "chalk" | "none";

export type SlideTheme = {
  id: SlideThemeId;
  label: string;
  descricao: string;
  /** Cores para a mini-prévia no seletor da UI. */
  preview: string[];
  fontHeading: string;
  fontBody: string;

  /** Capa */
  coverBgCss: string;
  coverBgHex: string;
  coverBgHex2: string;
  coverInk: string;
  coverMutedInk: string;
  coverBadgeBg: string;
  coverBadgeInk: string;

  /** Conteúdo */
  contentBgHex: string;
  pageBgCss: string;
  cardBgCss: string;
  cardBgHex: string;
  cardBorderCss: string;
  titleInk: string;
  bodyInk: string;
  mutedInk: string;
  accentHex: string;
  accentSoftCss: string;
  accentSoftHex: string;

  headerKind: SlideHeaderKind;
  decoration: SlideDecoration;
  /** Tema de fundo escuro (texto claro). */
  dark: boolean;
};

export const SLIDE_THEMES: Record<SlideThemeId, SlideTheme> = {
  moderno: {
    id: "moderno",
    label: "Moderno",
    descricao: "Gradiente vibrante, formas suaves e tipografia sem serifa",
    preview: ["#4f46e5", "#7c3aed", "#a78bfa"],
    fontHeading: "Calibri",
    fontBody: "Calibri",
    coverBgCss: "linear-gradient(135deg,#4f46e5 0%,#7c3aed 60%,#a855f7 100%)",
    coverBgHex: "4F46E5",
    coverBgHex2: "9333EA",
    coverInk: "FFFFFF",
    coverMutedInk: "E9D5FF",
    coverBadgeBg: "rgba(255,255,255,0.18)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "FFFFFF",
    pageBgCss: "#ffffff",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #e8e6f5",
    titleInk: "0F172A",
    bodyInk: "334155",
    mutedInk: "64748B",
    accentHex: "6D28D9",
    accentSoftCss: "#f5f3ff",
    accentSoftHex: "F5F3FF",
    headerKind: "bar",
    decoration: "blob",
    dark: false,
  },
  editorial: {
    id: "editorial",
    label: "Editorial",
    descricao: "Elegante, com serifa, tons creme e linhas finas",
    preview: ["#7c2d12", "#b45309", "#fde68a"],
    fontHeading: "Georgia",
    fontBody: "Georgia",
    coverBgCss: "linear-gradient(135deg,#fbf3e4 0%,#f6e7cf 100%)",
    coverBgHex: "FBF3E4",
    coverBgHex2: "F1E2C6",
    coverInk: "7C2D12",
    coverMutedInk: "92400E",
    coverBadgeBg: "rgba(124,45,18,0.10)",
    coverBadgeInk: "7C2D12",
    contentBgHex: "FBF7EF",
    pageBgCss: "#fbf7ef",
    cardBgCss: "#fffdf8",
    cardBgHex: "FFFDF8",
    cardBorderCss: "1px solid #e7d9bf",
    titleInk: "44260F",
    bodyInk: "4A3A28",
    mutedInk: "9A7B52",
    accentHex: "B45309",
    accentSoftCss: "#fdf4e3",
    accentSoftHex: "FDF4E3",
    headerKind: "underline",
    decoration: "line",
    dark: false,
  },
  minimal: {
    id: "minimal",
    label: "Minimalista",
    descricao: "Muito espaço, contraste sóbrio e detalhe fino",
    preview: ["#0f172a", "#475569", "#e2e8f0"],
    fontHeading: "Arial",
    fontBody: "Arial",
    coverBgCss: "linear-gradient(135deg,#ffffff 0%,#f1f5f9 100%)",
    coverBgHex: "FFFFFF",
    coverBgHex2: "F1F5F9",
    coverInk: "0F172A",
    coverMutedInk: "475569",
    coverBadgeBg: "rgba(15,23,42,0.06)",
    coverBadgeInk: "0F172A",
    contentBgHex: "FFFFFF",
    pageBgCss: "#ffffff",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #e2e8f0",
    titleInk: "0F172A",
    bodyInk: "334155",
    mutedInk: "94A3B8",
    accentHex: "0F172A",
    accentSoftCss: "#f1f5f9",
    accentSoftHex: "F1F5F9",
    headerKind: "underline",
    decoration: "line",
    dark: false,
  },
  vibrante: {
    id: "vibrante",
    label: "Vibrante",
    descricao: "Alto contraste, blocos coloridos e energia",
    preview: ["#e11d48", "#f59e0b", "#fb7185"],
    fontHeading: "Trebuchet MS",
    fontBody: "Trebuchet MS",
    coverBgCss: "linear-gradient(135deg,#e11d48 0%,#f43f5e 45%,#f59e0b 100%)",
    coverBgHex: "E11D48",
    coverBgHex2: "F59E0B",
    coverInk: "FFFFFF",
    coverMutedInk: "FFE4E6",
    coverBadgeBg: "rgba(255,255,255,0.2)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "FFF7F2",
    pageBgCss: "#fff7f2",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #fed7c3",
    titleInk: "9F1239",
    bodyInk: "44262B",
    mutedInk: "B45369",
    accentHex: "E11D48",
    accentSoftCss: "#ffe4e6",
    accentSoftHex: "FFE4E6",
    headerKind: "block",
    decoration: "corner",
    dark: false,
  },
  academico: {
    id: "academico",
    label: "Acadêmico",
    descricao: "Sóbrio, azul-marinho e faixas institucionais",
    preview: ["#0f2a4a", "#1d4ed8", "#bfdbfe"],
    fontHeading: "Georgia",
    fontBody: "Arial",
    coverBgCss: "linear-gradient(135deg,#0f2a4a 0%,#1e3a8a 100%)",
    coverBgHex: "0F2A4A",
    coverBgHex2: "1E3A8A",
    coverInk: "FFFFFF",
    coverMutedInk: "BFDBFE",
    coverBadgeBg: "rgba(255,255,255,0.16)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "FFFFFF",
    pageBgCss: "#f8fafc",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #dbe4f0",
    titleInk: "0F2A4A",
    bodyInk: "334155",
    mutedInk: "64748B",
    accentHex: "1D4ED8",
    accentSoftCss: "#eff6ff",
    accentSoftHex: "EFF6FF",
    headerKind: "ribbon",
    decoration: "line",
    dark: false,
  },
  lousa: {
    id: "lousa",
    label: "Lousa",
    descricao: "Quadro escolar escuro com destaque em giz",
    preview: ["#14302a", "#1f3b34", "#fcd34d"],
    fontHeading: "Trebuchet MS",
    fontBody: "Trebuchet MS",
    coverBgCss: "linear-gradient(135deg,#13302a 0%,#1c4038 100%)",
    coverBgHex: "13302A",
    coverBgHex2: "1C4038",
    coverInk: "F8FAFC",
    coverMutedInk: "FCD34D",
    coverBadgeBg: "rgba(252,211,77,0.18)",
    coverBadgeInk: "FCD34D",
    contentBgHex: "163A32",
    pageBgCss: "#163a32",
    cardBgCss: "#1c4038",
    cardBgHex: "1C4038",
    cardBorderCss: "1px solid #2c5249",
    titleInk: "F8FAFC",
    bodyInk: "E2E8F0",
    mutedInk: "9DBBB0",
    accentHex: "FCD34D",
    accentSoftCss: "rgba(252,211,77,0.14)",
    accentSoftHex: "234A41",
    headerKind: "chalk",
    decoration: "chalk",
    dark: true,
  },
  corporativo: {
    id: "corporativo",
    label: "Corporativo",
    descricao: "Azul-marinho sóbrio, faixas institucionais e tipografia executiva",
    preview: ["#0f2942", "#1e4976", "#cbd5e1"],
    fontHeading: "Calibri",
    fontBody: "Calibri",
    coverBgCss: "linear-gradient(135deg,#0f2942 0%,#1e3a5f 55%,#2d4a6f 100%)",
    coverBgHex: "0F2942",
    coverBgHex2: "2D4A6F",
    coverInk: "FFFFFF",
    coverMutedInk: "CBD5E1",
    coverBadgeBg: "rgba(255,255,255,0.14)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "F8FAFC",
    pageBgCss: "#f1f5f9",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #d8e0ea",
    titleInk: "0F2942",
    bodyInk: "334155",
    mutedInk: "64748B",
    accentHex: "1E4976",
    accentSoftCss: "#e8eef5",
    accentSoftHex: "E8EEF5",
    headerKind: "ribbon",
    decoration: "line",
    dark: false,
  },
  neontech: {
    id: "neontech",
    label: "Neon Tech",
    descricao: "Fundo escuro com acentos ciano e roxo — ideal para STEM e tecnologia",
    preview: ["#0a0f1e", "#00e5ff", "#a855f7"],
    fontHeading: "Trebuchet MS",
    fontBody: "Trebuchet MS",
    coverBgCss: "linear-gradient(135deg,#0a0f1e 0%,#151b33 50%,#1a1040 100%)",
    coverBgHex: "0A0F1E",
    coverBgHex2: "1A1040",
    coverInk: "F0FDFF",
    coverMutedInk: "00E5FF",
    coverBadgeBg: "rgba(0,229,255,0.16)",
    coverBadgeInk: "00E5FF",
    contentBgHex: "111827",
    pageBgCss: "#0d1117",
    cardBgCss: "#151b2e",
    cardBgHex: "151B2E",
    cardBorderCss: "1px solid #2a3555",
    titleInk: "F0FDFF",
    bodyInk: "CBD5E1",
    mutedInk: "7B8BA8",
    accentHex: "00E5FF",
    accentSoftCss: "rgba(0,229,255,0.12)",
    accentSoftHex: "1A2A40",
    headerKind: "bar",
    decoration: "dots",
    dark: true,
  },
  infografico: {
    id: "infografico",
    label: "Infográfico",
    descricao: "Blocos modulares e paleta teal — perfeito para dados, gráficos e comparações",
    preview: ["#0e7490", "#14b8a6", "#ccfbf1"],
    fontHeading: "Arial",
    fontBody: "Arial",
    coverBgCss: "linear-gradient(135deg,#0e7490 0%,#0891b2 45%,#14b8a6 100%)",
    coverBgHex: "0E7490",
    coverBgHex2: "14B8A6",
    coverInk: "FFFFFF",
    coverMutedInk: "CCFBF1",
    coverBadgeBg: "rgba(255,255,255,0.2)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "F0FDFA",
    pageBgCss: "#f0fdfa",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #99f6e4",
    titleInk: "134E4A",
    bodyInk: "115E59",
    mutedInk: "5EEAD4",
    accentHex: "0D9488",
    accentSoftCss: "#ccfbf1",
    accentSoftHex: "CCFBF1",
    headerKind: "block",
    decoration: "corner",
    dark: false,
  },
  pastel: {
    id: "pastel",
    label: "Pastel Educativo",
    descricao: "Tons suaves e acolhedores — ótimo para anos iniciais e conteúdo lúdico",
    preview: ["#fbcfe8", "#c4b5fd", "#fef08a"],
    fontHeading: "Calibri",
    fontBody: "Calibri",
    coverBgCss: "linear-gradient(135deg,#fbcfe8 0%,#e9d5ff 50%,#fef08a 100%)",
    coverBgHex: "FBCFE8",
    coverBgHex2: "FEF08A",
    coverInk: "5B21B6",
    coverMutedInk: "7C3AED",
    coverBadgeBg: "rgba(91,33,182,0.10)",
    coverBadgeInk: "5B21B6",
    contentBgHex: "FFFBFE",
    pageBgCss: "#fffafe",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #f3e8ff",
    titleInk: "5B21B6",
    bodyInk: "4C1D95",
    mutedInk: "A78BFA",
    accentHex: "8B5CF6",
    accentSoftCss: "#f5f3ff",
    accentSoftHex: "F5F3FF",
    headerKind: "underline",
    decoration: "blob",
    dark: false,
  },
  natureza: {
    id: "natureza",
    label: "Natureza",
    descricao: "Verdes orgânicos e tons terrosos — ciências, meio ambiente e biologia",
    preview: ["#14532d", "#16a34a", "#dcfce7"],
    fontHeading: "Georgia",
    fontBody: "Arial",
    coverBgCss: "linear-gradient(135deg,#14532d 0%,#166534 50%,#15803d 100%)",
    coverBgHex: "14532D",
    coverBgHex2: "15803D",
    coverInk: "FFFFFF",
    coverMutedInk: "BBF7D0",
    coverBadgeBg: "rgba(255,255,255,0.16)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "F0FDF4",
    pageBgCss: "#f0fdf4",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #bbf7d0",
    titleInk: "14532D",
    bodyInk: "166534",
    mutedInk: "4ADE80",
    accentHex: "16A34A",
    accentSoftCss: "#dcfce7",
    accentSoftHex: "DCFCE7",
    headerKind: "bar",
    decoration: "line",
    dark: false,
  },
  geometria: {
    id: "geometria",
    label: "Geometria",
    descricao: "Formas angulares, contraste índigo-laranja — matemática e raciocínio lógico",
    preview: ["#312e81", "#f97316", "#fef3c7"],
    fontHeading: "Arial",
    fontBody: "Arial",
    coverBgCss: "linear-gradient(135deg,#312e81 0%,#4338ca 40%,#f97316 100%)",
    coverBgHex: "312E81",
    coverBgHex2: "F97316",
    coverInk: "FFFFFF",
    coverMutedInk: "FEF3C7",
    coverBadgeBg: "rgba(255,255,255,0.18)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "FFFBEB",
    pageBgCss: "#fffbeb",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #fde68a",
    titleInk: "312E81",
    bodyInk: "4338CA",
    mutedInk: "F97316",
    accentHex: "F97316",
    accentSoftCss: "#fef3c7",
    accentSoftHex: "FEF3C7",
    headerKind: "block",
    decoration: "corner",
    dark: false,
  },
  retro: {
    id: "retro",
    label: "Retro",
    descricao: "Paleta quente anos 70, serifas clássicas — história, artes e cultura",
    preview: ["#78350f", "#ea580c", "#fef9c3"],
    fontHeading: "Georgia",
    fontBody: "Georgia",
    coverBgCss: "linear-gradient(135deg,#78350f 0%,#c2410c 50%,#ea580c 100%)",
    coverBgHex: "78350F",
    coverBgHex2: "EA580C",
    coverInk: "FEF9C3",
    coverMutedInk: "FDE68A",
    coverBadgeBg: "rgba(254,249,195,0.18)",
    coverBadgeInk: "FEF9C3",
    contentBgHex: "FFFBEB",
    pageBgCss: "#fffbeb",
    cardBgCss: "#fffdf5",
    cardBgHex: "FFFDF5",
    cardBorderCss: "1px solid #fde68a",
    titleInk: "78350F",
    bodyInk: "92400E",
    mutedInk: "D97706",
    accentHex: "EA580C",
    accentSoftCss: "#fef3c7",
    accentSoftHex: "FEF3C7",
    headerKind: "underline",
    decoration: "blob",
    dark: false,
  },
  luxo: {
    id: "luxo",
    label: "Luxo",
    descricao: "Preto e dourado com serifas — formaturas, eventos especiais e apresentações formais",
    preview: ["#1c1917", "#ca8a04", "#fef3c7"],
    fontHeading: "Georgia",
    fontBody: "Georgia",
    coverBgCss: "linear-gradient(135deg,#1c1917 0%,#292524 50%,#44403c 100%)",
    coverBgHex: "1C1917",
    coverBgHex2: "44403C",
    coverInk: "FEF3C7",
    coverMutedInk: "CA8A04",
    coverBadgeBg: "rgba(202,138,4,0.22)",
    coverBadgeInk: "FEF3C7",
    contentBgHex: "1C1917",
    pageBgCss: "#171412",
    cardBgCss: "#292524",
    cardBgHex: "292524",
    cardBorderCss: "1px solid #57534e",
    titleInk: "FEF3C7",
    bodyInk: "E7E5E4",
    mutedInk: "A8A29E",
    accentHex: "CA8A04",
    accentSoftCss: "rgba(202,138,4,0.14)",
    accentSoftHex: "3D3528",
    headerKind: "ribbon",
    decoration: "line",
    dark: true,
  },
  startup: {
    id: "startup",
    label: "Startup",
    descricao: "Gradiente moderno índigo-rosa, layout limpo — empreendedorismo e inovação",
    preview: ["#4f46e5", "#ec4899", "#f8fafc"],
    fontHeading: "Calibri",
    fontBody: "Calibri",
    coverBgCss: "linear-gradient(135deg,#4f46e5 0%,#7c3aed 40%,#ec4899 100%)",
    coverBgHex: "4F46E5",
    coverBgHex2: "EC4899",
    coverInk: "FFFFFF",
    coverMutedInk: "FBCFE8",
    coverBadgeBg: "rgba(255,255,255,0.18)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "FFFFFF",
    pageBgCss: "#f8fafc",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #e2e8f0",
    titleInk: "312E81",
    bodyInk: "4338CA",
    mutedInk: "818CF8",
    accentHex: "EC4899",
    accentSoftCss: "#fdf2f8",
    accentSoftHex: "FDF2F8",
    headerKind: "bar",
    decoration: "dots",
    dark: false,
  },
  oceano: {
    id: "oceano",
    label: "Oceano",
    descricao: "Azuis profundos em camadas — geografia, física e conteúdos científicos",
    preview: ["#0369a1", "#0ea5e9", "#e0f2fe"],
    fontHeading: "Calibri",
    fontBody: "Calibri",
    coverBgCss: "linear-gradient(135deg,#0369a1 0%,#0284c7 45%,#0ea5e9 100%)",
    coverBgHex: "0369A1",
    coverBgHex2: "0EA5E9",
    coverInk: "FFFFFF",
    coverMutedInk: "E0F2FE",
    coverBadgeBg: "rgba(255,255,255,0.18)",
    coverBadgeInk: "FFFFFF",
    contentBgHex: "F0F9FF",
    pageBgCss: "#f0f9ff",
    cardBgCss: "#ffffff",
    cardBgHex: "FFFFFF",
    cardBorderCss: "1px solid #bae6fd",
    titleInk: "0C4A6E",
    bodyInk: "0369A1",
    mutedInk: "38BDF8",
    accentHex: "0284C7",
    accentSoftCss: "#e0f2fe",
    accentSoftHex: "E0F2FE",
    headerKind: "ribbon",
    decoration: "blob",
    dark: false,
  },
};

export function resolveSlideTheme(value: unknown): SlideTheme {
  const id = String(value || "").toLowerCase();
  if ((SLIDE_THEME_IDS as readonly string[]).includes(id)) {
    return SLIDE_THEMES[id as SlideThemeId];
  }
  return SLIDE_THEMES.moderno;
}

/** Metadados leves para o seletor da UI (sem expor todos os tokens). */
export const SLIDE_THEME_OPTIONS = SLIDE_THEME_IDS.map((id) => ({
  id,
  label: SLIDE_THEMES[id].label,
  descricao: SLIDE_THEMES[id].descricao,
  preview: SLIDE_THEMES[id].preview,
  dark: SLIDE_THEMES[id].dark,
}));
